[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[customizations.flatpaks]
remotes = [
  { name = "flathub", url = "https://flathub.org/repo/flathub.flatpakrepo" }
]
install = [
  "dev.zelikos.rollit",
  "com.spotify.Client"
]